### ISSUE TITLE
I am using with Synology Nas. One problem I found is that how to export PDF report for later usage?

### ISSUE THREAD

**Issue by Stromtr00per** [rogerrum/docker-oscar#1]
There is some problem about permission that won’t allow me to save PDF to destination folder.

CPAP data reading is perfectly fine. But, I cannot save anything.

![A9A0E5FE-706D-4BE5-A882-7646FB3E13B6](https://user-images.githubusercontent.com/86898061/204130379-042f80af-259b-42ed-ab7d-a1419c41a3fd.jpeg)

**Comment by rogerrum** [comment]
Seems like the folder permission issue on your NAS. I think the folder you used as volume is readonly.

You can also check the actual permissions while using in browser using terminal. on the VNC window, right click and select terminal and check in there.

I run this image on Kube. Here is my config  https://github.com/rogerrum/k8s-gitops/tree/main/main/homelab/oscar
